export const techStack = [
    "Assembly Language","jsreact", "Ada", "ALGOL", "APL", "AWK", "Bash", "BASIC", "C", "C++", "C#",
    "COBOL", "Clojure", "Crystal", "D", "Dart", "Delphi/Object Pascal", "Eiffel", "Elixir",
    "Elm", "Erlang", "F#", "Forth", "Fortran", "Go", "Groovy", "Haskell", "HTML/CSS",
    "Java", "JavaScript", "Julia", "Kotlin", "LabVIEW", "Ladder Logic", "Lisp", "Lua",
    "MATLAB", "ML", "Modula-2", "Nim", "Objective-C", "OCaml", "OpenCL", "Pascal", "Perl",
    "PHP", "PL/I", "PL/SQL", "PostScript", "Prolog", "PureScript", "Python", "R", "Racket",
    "Ruby", "Rust", "Scala", "Scheme", "Shell Scripting", "Smalltalk", "SQL", "Swift",
    "Tcl", "TypeScript", "VHDL", "Verilog", "Visual Basic", "WebAssembly", "Wolfram Language",
    "AI/ML Technologies", "TensorFlow", "PyTorch", "Keras", "scikit-learn", "OpenCV",
    "NLTK", "Hugging Face Transformers", "XGBoost", "LightGBM", "FastAI", "Dask",
    "Big Data Technologies", "Hadoop", "Spark", "Kafka", "Flink", "Storm", "Hive", "Pig",
    "Database Technologies", "MySQL", "PostgreSQL", "MongoDB", "Cassandra", "Redis",
    "Neo4j", "Elasticsearch", "SQLite", "MariaDB", "Firebase", "GraphQL", "DynamoDB",
    "Full Stack Technologies", "MERN Stack", "MEAN Stack", "LAMP Stack", "JAMstack",
    "DevOps Technologies", "Docker", "Kubernetes", "Jenkins", "Git", "GitHub Actions",
    "Ansible", "Terraform", "Chef", "Puppet", "Nagios", "Prometheus", "Grafana","Nodejs",
    "Web Frameworks", "React", "Vue.js", "Angular", "Svelte", "Next.js", "Nuxt.js",
    "NestJS", "Express.js", "Django", "Flask", "FastAPI", "Spring Boot", "Ruby on Rails",
    "Laravel", "ASP.NET Core", "Mobile App Frameworks", "React Native", "Flutter",
    "SwiftUI", "Jetpack Compose", "Ionic", "Xamarin", "Game Development Technologies",
    "Unity", "Unreal Engine", "Godot", "CryEngine", "Pygame", "Phaser", "LibGDX",
    "Networking Technologies", "REST", "GraphQL", "gRPC", "WebSockets", "MQTT","Git",
    "Security Technologies", "OAuth", "JWT", "SSO", "SAML", "OpenID Connect", "AES",
    "Cryptography Libraries", "bcrypt", "Argon2", "scrypt", "MD5", "SHA-256",
    "Blockchain Technologies", "Ethereum", "Solidity", "Hyperledger", "Cardano",
    "Polkadot", "Cosmos", "Cryptocurrency Technologies", "Bitcoin", "Ripple", "Litecoin",
    "Software Development Tools", "VS Code", "PyCharm", "IntelliJ IDEA", "Eclipse",
    "NetBeans", "Xcode", "Android Studio", "Sublime Text", "Atom", "Emacs", "Vim",
    "Programming Paradigms", "Object-Oriented Programming", "Functional Programming",
    "Procedural Programming", "Event-Driven Programming", "Aspect-Oriented Programming",
    "Cloud Technologies", "AWS", "Google Cloud", "Microsoft Azure", "IBM Cloud",
    "Serverless Frameworks", "AWS Lambda", "Google Cloud Functions", "Azure Functions",
    "Edge Computing", "Content Delivery Networks (CDN)", "Cloudflare", "Akamai",
    "Machine Learning Services", "AWS SageMaker", "Google AI Platform", "Azure ML",
    "Testing Frameworks", "Jest", "Mocha", "Jasmine", "Cypress", "Selenium", "Puppeteer",
    "Playwright", "JUnit", "PyTest", "RSpec", "CI/CD Pipelines", "Travis CI", "CircleCI",
    "GitHub Actions", "GitLab CI/CD", "Bitbucket Pipelines", "Database Scaling",
    "Sharding", "Replication", "Load Balancing", "Indexing", "Data Warehousing",
    "ETL Tools", "Apache Nifi", "Airflow", "Talend", "Pentaho", "AI Chatbot Frameworks",
    "Rasa", "Dialogflow", "IBM Watson Assistant", "Microsoft Bot Framework",
    "IoT Technologies", "Arduino", "Raspberry Pi", "ESP8266", "ESP32", "MQTT", "Zigbee",
    "5G Technologies", "Edge AI", "AI Hardware", "TPUs", "NPUs", "Quantum Computing",
    "IBM Q", "D-Wave", "AWS Braket", "Cryptography Techniques", "Homomorphic Encryption",
    "Zero-Knowledge Proofs", "Blockchain Smart Contracts", "Web3.js", "Ether.js",
    "Decentralized Storage", "IPFS", "Arweave", "Cloud Security", "IAM", "SIEM",
    "Cloud Native Technologies", "Service Mesh", "Istio", "Linkerd","Tailwind","UI","UX"
  ];